org.gradle.jvmargs = -Xmx6G
org.gradle.java.installations.auto-download=false
org.gradle.parallel = true
org.gradle.caching = true

# Mod Info
mod_id = gtceu
mod_name = GoblinTechMotive
mod_version = 0.0.1-gtmotive
create_mod_version = 6.0.10
deployer_mod_version = 0.1.2
tfc_mod_version = 4.1.2
advancedxray_mod_version = 21.0.0
neoecoae_mod_version = 1.3.4
ldlib2_mod_version = 2.2.12
mod_description = GoblinTechMotive - GoblinCoders 整合包专用 GregTech CEu 核心模组，依赖 Create、AE2、NeoEcoAE
mod_license = LGPL-3.0 license
mod_url = https://github.com/dalizi2333/GoblinTechMotiveCore
mod_issue_tracker = https://github.com/dalizi2333/GoblinTechMotiveCore/issues/
maven_group = com.goblincoders
