org.gradle.jvmargs = -Xmx6G
org.gradle.java.installations.auto-download=false
org.gradle.parallel = true
org.gradle.caching = true

# Mod Info
mod_id = goblintechmotive
mod_name = GoblinTechMotive
mod_version = 0.0.1-alpha
mod_description = GoblinTechMotive - 整合包专用 GregTech CEu 核心模组，依赖 Create、AE2、NeoEcoAE
mod_license = LGPL-3.0 license
mod_url = https://github.com/dalizi2333/GoblinTechMotiveCore
mod_issue_tracker = https://github.com/dalizi2333/GoblinTechMotiveCore/issues/
maven_group = com.gregtechceu.gtceu
